### ISSUE TITLE
Possibility to sell FTO

### ISSUE THREAD

**Issue by michalsikora** [GENERALBYTESCOM/batm_public#93] opened 2018-08-02 16:33 UTC
Hi,

we have question about run sell option for FuturoCoin. Is it possible to implement sell FTO coins using current interfaces? Currently we have implementation for `IRateSourceAdvanced` below

https://github.com/GENERALBYTESCOM/batm_public/blob/master/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/futurocoin/sources/yobit/YobitRateSource.java#L12

but we can see in our application server that is not enough to have sell tab for mentioned coin.

Thanks

**Comment by rpanak-generalbytes** [comment] 2018-08-07 07:10
@jeerhsandeep can't tell you anything more specific. I'd recommend watching the repository for changes.

However, when the commit arrives, there will be an example implementation available that will show you what needs to be done for sell to work.

**Comment by sumcoinlabs** [comment] 2018-08-15 10:26
Hi GB Team,
We have updated our client to V 0.16.1 and are excited to see 2 way support for coins other than BTC/LTC etc.    Being an Index coin, this is a vital function for GB operators and their customers.   Our question becomes, what do we need to do if anything for that 2 way (sell) function.  Or, will we be notified prior to feature release?   I'm seeing end of the month above but curious.

**Comment by rpanak-generalbytes** [comment] 2018-08-20 10:28
@sumcoinlabs there has been a commit enabling you to start implementation. Another commit with a sample implementation should follow late August/early September. Each currency will have to supply a sell implementation to enable 2-way transactions.

**Comment by michalsikora** [comment] 2018-09-13 17:08
Hi,

any update about sell extension for altcoins?

Thanks

**Comment by sumcoinlabs** [comment] 2018-09-26 03:33
> @sumcoinlabs there has been a commit enabling you to start implementation. 

"Another commit with a sample implementation should follow late August/early September. "
Did this happen? Where to see?

"Each currency will have to supply a sell implementation to enable 2-way transactions."  
Documentation?

Looking where these can it be found?

Thanks

**Comment by rpanak-generalbytes** [comment] 2018-09-26 11:32
Hi. The example implementation is still WiP. Some unexpected tasks with bigger priority have surfaced, so the implementation got postponed.

**Comment by sumcoinlabs** [comment] 2018-09-30 11:00
> Hi. The example implementation is still WiP. Some unexpected tasks with bigger priority have surfaced, so the implementation got postponed.

Until how long?   Could we just add a sources file with our API like Dash did?

**Comment by LudmilaSa** [comment] 2018-10-24 06:58
**GeneralBytes** What about sell altcoin feature?
Is an example implementation for one of the altcoins added? 
You wrote that it will be ready at the end of August.

Thanks.

**Comment by generalbytes** [comment] 2018-10-26 15:41
We are still working on it. Example support is being implemented for BCH. Please stay tuned.

**Comment by PatrycjaFTO** [comment] 2019-01-02 13:18
Hello, @generalbytes can you please let us know what is going on with this topic, we have been waiting for extremly long time and it looks like nothing is happening.

**Comment by generalbytes** [comment] 2019-01-02 14:58
We have it ready. We just didn't want to release it during holiday time period to avoid issues.
It will be release next week on 8th January.

**Comment by DeanJayEm** [comment] 2019-01-09 07:05
hi, @generalbytes have u release it yet?

**Comment by sumcoinlabs** [comment] 2019-01-09 07:55
When there’s an update on this issue, we’d appreciate a post and link to the instructions also.   

Hope you guys had a great holiday and welcome back

**Comment by DeanJayEm** [comment] 2019-01-16 01:21
Hi @generalbytes can we have at least a response from you?

**Comment by rpanak-generalbytes** [comment] 2019-01-16 10:39
Hi @DeanJayEm,
we're sorry it's taking so long. We don't like to give dates because they are just estimates subject to change according to the current situation and the public (understandably) doesn't like when we don't make it.
That being said, the current situation is the following: the feature is implemented and is currently in testing. In case of no further issues, we **estimate** it to be merged at the beginning of February. It is currently one of our priorities.

**Comment by int3hh** [comment] 2019-01-18 22:36
Hello, we need this feature too. Please push it in a separate branch and we can help with tests.

**Comment by sumcoinlabs** [comment] 2019-01-18 22:39
We would appreciate a separate branch release also

**Comment by rpanak-generalbytes** [comment] 2019-01-25 11:58
We will notify you once the code has been made available here on GitHub.

**Comment by sumcoinlabs** [comment] 2019-02-09 07:56
Looking for an update on this

**Comment by int3hh** [comment] 2019-02-09 22:26
when update ?

**Comment by generalbytes** [comment] 2019-02-13 00:01
Here is example implementation for BitcoinCash.
https://github.com/GENERALBYTESCOM/batm_public/commit/b4c98398a7efdbb18da93ed6c5ab53c1a5744e0c

**Comment by enriquesouza** [comment] 2019-02-13 01:10
I am implementing sell to SmartCash. So, can I base myself in this example?

**Comment by generalbytes** [comment] 2019-02-13 20:34
Here is example implementation for Sumcoin(not tested).
https://github.com/GENERALBYTESCOM/batm_public/commit/57a4af5a16c8e89ada78b2e0194bf1d0b9bd7413
You can base your coin 2-way support on BitcoinCash or Sumcoin.

**Comment by generalbytes** [comment] 2019-02-13 20:41
You will also need Server and terminal version 20190213 or higher.

**Comment by int3hh** [comment] 2019-02-13 22:36
thank you will check it out!

**Comment by sumcoinlabs** [comment] 2019-02-14 01:35
> Here is example implementation for Sumcoin(not tested).
> [57a4af5](https://github.com/GENERALBYTESCOM/batm_public/commit/57a4af5a16c8e89ada78b2e0194bf1d0b9bd7413)
> You can base your coin 2-way support on BitcoinCash or Sumcoin.

Pulled version 20190213 and tested.   Sumcoin still needs Sumcoind Sell Exchange Strategy added, otherwise, tests come back working.   Hope this helps others if using Sumcoin as a template

**Comment by sumcoinlabs** [comment] 2019-02-14 01:45
> Here is example implementation for Sumcoin(not tested).
> [57a4af5](https://github.com/GENERALBYTESCOM/batm_public/commit/57a4af5a16c8e89ada78b2e0194bf1d0b9bd7413)
> You can base your coin 2-way support on BitcoinCash or Sumcoin.

Sell exchange strategy (1) - Receive Coins to Hot Wallet still needs to be added.   Otherwise, tests come back good for Sumcoin.   Currently in 20190213, there is no Sell exchange strategy for Sumcoin.     Hope this helps others

**Comment by generalbytes** [comment] 2019-02-14 06:33
> Sell exchange strategy (1) - Receive Coins to Hot Wallet still needs to be added. Otherwise, tests come back good for Sumcoin. Currently in 20190213, there is no Sell exchange strategy for Sumcoin. Hope this helps others

It is fixed in 20190214.

**Comment by sumcoinlabs** [comment] 2019-02-14 06:34
Updated to 20190214 and all systems working

**Comment by generalbytes** [comment] 2019-02-14 10:18
There has been some improvements in this commit. 
https://github.com/GENERALBYTESCOM/batm_public/commit/f494a5cb40ff04d0318f422f978ecacb3da0bea0

If you have 20190214 please reinstall it(yes, we are able to release multiple releases with same build number) as it contains these fixes.

**Comment by generalbytes** [comment] 2019-02-14 12:36
Sumcoin is now working too. I had to do some modifications to work with core v0.16. 
Sumcoind has to be run with **-deprecatedrpc=estimatefee** to support estimatefee
`./sumcoind -rpcuser=rpcuser -rpcpassword=rpcpassword -rpcport=3332 -deprecatedrpc=estimatefee`
First successful withdrawal transaction is her(confirmation time was great compared to bitcoincash): 
http://159.65.72.249:3001/address/2PnYyjSSrdRuy8PqiFLo6fjSxpHtZ2cQh2L

Code changes are here: https://github.com/GENERALBYTESCOM/batm_public/commit/3db9b80c69b5566622a0b3efd31ec595c2e5e543
Please reinstall server to version 20190214 again it contains above commit.

**Comment by enriquesouza** [comment] 2019-02-14 15:30
@generalbytes after that upgrade you suggested me. Everything stopped working. Not even SmartCash's log is showing now int the terminal.

**Comment by enriquesouza** [comment] 2019-02-14 15:31
cd /batm/ && ./batm-manage upgrade-server 20190214
cd /batm/ && ./batm-manage upgrade-terminal 20190214 SERIAL

**Comment by enriquesouza** [comment] 2019-02-14 15:36
@generalbytes , about the error. 
02:40:30.045 [RPCBlockchainWatcher] ERROR batm.master.RPCPaymentSupport - wf.bitcoin.javabitcoindrpcclient.BitcoinJSONRPCClient$TransactionWrapper cannot be cast to wf.bitcoin.javabitcoindrpcclient.BitcoindRpcClient$RawTransaction

There is a bug in the code. I debugged and saw the type is wrong. 

here is the right code:
/Users/enriquesouza/git/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/common/AbstractRPCPaymentSupport.java

        @Override
        public void numberOfConfirmationsChanged(String cryptoCurrency, String transactionHash, Object tag,
                int numberOfConfirmations) {
            try {
                if (incomingTransactions.size() > 0 && request.getState() != PaymentRequest.STATE_REMOVED) {
                    if (!seenInBlockChain) {

                        **boolean performConfirmation = false;
                        BitcoindRpcClient.Transaction transaction = (BitcoindRpcClient.Transaction) tag;**

                        if (incomingTransactions.size() > 0 && hasHashOfOne(### transaction.raw(), incomingTransactions)) {
                            log_debug("PaymentTransactionListener.numberOfConfirmationsChanged - Incoming payment "
                                    + request.getAddress() + " appeared in blockchain (" + numberOfConfirmations
                                    + "). Confirmed.");
                            performConfirmation = true;
                            seenInBlockChain = true;
                        }

                        if (performConfirmation) {
                            int previousState = request.getState();
                            request.setState(PaymentRequest.STATE_SEEN_IN_BLOCK_CHAIN);
                            fireStateChanged(request, previousState);
                        }
                    }

                    if (request.getState() == PaymentRequest.STATE_SEEN_IN_BLOCK_CHAIN) {
                        if (numberOfConfirmations > 0) {

                            BitcoindRpcClient.Transaction transaction = (BitcoindRpcClient.Transaction) tag;
                            IPaymentRequestListener.Direction direction = IPaymentRequestListener.Direction.INCOMING;
                            if (hasHashOfOne(transaction.raw(), outgoingTransactions)) {
                                direction = IPaymentRequestListener.Direction.OUTGOING;
                            }
                            fireNumberOfConfirmationsChanged(request, numberOfConfirmations, direction);
                            // transaction is waiting to be removed
                            if (direction == IPaymentRequestListener.Direction.INCOMING) {
                                if (numberOfConfirmations >= request
                                        .getRemoveAfterNumberOfConfirmationsOfIncomingTransaction()) {
                                    request.setRemovalConditionForIncomingTransaction();
                                }
                            } else {
                                if (numberOfConfirmations >= request
                                        .getRemoveAfterNumberOfConfirmationsOfOutgoingTransaction()) {
                                    request.setRemovalConditionForOutgoingTransaction();
                                }
                            }
                            if (request.isRemovalCondition()) {
                                int previousState = request.getState();
                                request.setState(PaymentRequest.STATE_REMOVED);
                                stopListening();
                                fireStateChanged(request, previousState);
                            }
                        }
                    }
                }
            } catch (Exception ex) {
                log.error(ex.getMessage());
                System.out.println(ex.getMessage());
            }
        }

**Comment by generalbytes** [comment] 2019-02-14 15:43
> @generalbytes after that upgrade you suggested me. Everything stopped working. Not even SmartCash's log is showing now int the terminal.

Terminal is not supposed to show SmartCash's log.

**Comment by generalbytes** [comment] 2019-02-14 15:45
> @generalbytes , about the error.
> 02:40:30.045 [RPCBlockchainWatcher] ERROR batm.master.RPCPaymentSupport - wf.bitcoin.javabitcoindrpcclient.BitcoinJSONRPCClient$TransactionWrapper cannot be cast to wf.bitcoin.javabitcoindrpcclient.BitcoindRpcClient$RawTransaction
> 
> There is a bug in the code. I debugged and saw the type is wrong.
> 
> here is the right code:
> /Users/enriquesouza/git/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/common/AbstractRPCPaymentSupport.java
> 
> ```
>     @Override
>     public void numberOfConfirmationsChanged(String cryptoCurrency, String transactionHash, Object tag,
>             int numberOfConfirmations) {
>         try {
>             if (incomingTransactions.size() > 0 && request.getState() != PaymentRequest.STATE_REMOVED) {
>                 if (!seenInBlockChain) {
> 
>                     boolean performConfirmation = false;
>                     BitcoindRpcClient.Transaction transaction = (BitcoindRpcClient.Transaction) tag;
> 
>                     if (incomingTransactions.size() > 0 && hasHashOfOne(transaction.raw(), incomingTransactions)) {
>                         log_debug("PaymentTransactionListener.numberOfConfirmationsChanged - Incoming payment "
>                                 + request.getAddress() + " appeared in blockchain (" + numberOfConfirmations
>                                 + "). Confirmed.");
>                         performConfirmation = true;
>                         seenInBlockChain = true;
>                     }
> 
>                     if (performConfirmation) {
>                         int previousState = request.getState();
>                         request.setState(PaymentRequest.STATE_SEEN_IN_BLOCK_CHAIN);
>                         fireStateChanged(request, previousState);
>                     }
>                 }
> 
>                 if (request.getState() == PaymentRequest.STATE_SEEN_IN_BLOCK_CHAIN) {
>                     if (numberOfConfirmations > 0) {
> 
>                         BitcoindRpcClient.Transaction transaction = (BitcoindRpcClient.Transaction) tag;
>                         IPaymentRequestListener.Direction direction = IPaymentRequestListener.Direction.INCOMING;
>                         if (hasHashOfOne(transaction.raw(), outgoingTransactions)) {
>                             direction = IPaymentRequestListener.Direction.OUTGOING;
>                         }
>                         fireNumberOfConfirmationsChanged(request, numberOfConfirmations, direction);
>                         // transaction is waiting to be removed
>                         if (direction == IPaymentRequestListener.Direction.INCOMING) {
>                             if (numberOfConfirmations >= request
>                                     .getRemoveAfterNumberOfConfirmationsOfIncomingTransaction()) {
>                                 request.setRemovalConditionForIncomingTransaction();
>                             }
>                         } else {
>                             if (numberOfConfirmations >= request
>                                     .getRemoveAfterNumberOfConfirmationsOfOutgoingTransaction()) {
>                                 request.setRemovalConditionForOutgoingTransaction();
>                             }
>                         }
>                         if (request.isRemovalCondition()) {
>                             int previousState = request.getState();
>                             request.setState(PaymentRequest.STATE_REMOVED);
>                             stopListening();
>                             fireStateChanged(request, previousState);
>                         }
>                     }
>                 }
>             }
>         } catch (Exception ex) {
>             log.error(ex.getMessage());
>             System.out.println(ex.getMessage());
>         }
>     }
> ```

That was already fixed in commit f494a5cb40ff04d0318f422f978ecacb3da0bea0.

**Comment by enriquesouza** [comment] 2019-02-14 16:03
> > @generalbytes after that upgrade you suggested me. Everything stopped working. Not even SmartCash's log is showing now int the terminal.
> 
> Terminal is not supposed to show SmartCash's log.

I mean the LOGO (BRAND). It vanished after I upgraded the server. The code is running perfectly locally. 

All extensions are OK locally, but not in the terminal anymore.

**Comment by enriquesouza** [comment] 2019-02-14 16:04
Enriques-MacBook-Pro:batm_public_server enriquesouza$ git fetch
remote: Enumerating objects: 39, done.
remote: Counting objects: 100% (39/39), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 39 (delta 18), reused 38 (delta 17), pack-reused 0
Unpacking objects: 100% (39/39), done.
From https://github.com/GENERALBYTESCOM/batm_public
   57a4af5..3db9b80  master     -> origin/master

I am using the last version

**Comment by sumcoinlabs** [comment] 2019-02-14 16:05
Are you upgrading BOTH CAS and the ATM?

**Comment by enriquesouza** [comment] 2019-02-14 16:07
@sumcoinlabs , I am not 100% sure, but I run the cmd
cd /batm/ && ./batm-manage upgrade-server 20190214
cd /batm/ && ./batm-manage upgrade-terminal 20190214 SERIAL

Should I use any other cmd too? I appreciate your help.

**Comment by sumcoinlabs** [comment] 2019-02-14 16:09
cd /batm/
./batm-manage upgrade-terminal 20190214 ‘ATM SERIAL NUMBER’

**Comment by enriquesouza** [comment] 2019-02-14 16:11
root@testBATM:/batm# cd /batm/ && ./batm-manage upgrade-terminal 20190214 "BT..."
Current Server version is 20190214 and requested terminal version is 20190214.
Checking license online...
License number XXXXXXX is valid.
Using existing terminal upgrade package 20190214...
Sending upgrade command to terminal BT.....
root@testBATM:/batm#

**Comment by sumcoinlabs** [comment] 2019-02-14 16:13
Looks good

**Comment by enriquesouza** [comment] 2019-02-14 16:15
> Looks good

It still not working... :(

**Comment by generalbytes** [comment] 2019-02-14 16:15
> Enriques-MacBook-Pro:batm_public_server enriquesouza$ git fetch
> remote: Enumerating objects: 39, done.
> remote: Counting objects: 100% (39/39), done.
> remote: Compressing objects: 100% (10/10), done.
> remote: Total 39 (delta 18), reused 38 (delta 17), pack-reused 0
> Unpacking objects: 100% (39/39), done.
> From https://github.com/GENERALBYTESCOM/batm_public
> [57a4af5](https://github.com/GENERALBYTESCOM/batm_public/commit/57a4af5a16c8e89ada78b2e0194bf1d0b9bd7413)..[3db9b80](https://github.com/GENERALBYTESCOM/batm_public/commit/3db9b80c69b5566622a0b3efd31ec595c2e5e543) master -> origin/master
> 
> I am using the last version

Where is your SmartCash source code with two way support added? I don't see your fork.

**Comment by enriquesouza** [comment] 2019-02-14 16:20
I just cloned, but I will fork right now

**Comment by enriquesouza** [comment] 2019-02-14 18:08
@generalbytes https://github.com/enriquesouza/batm_public

**Comment by generalbytes** [comment] 2019-02-14 19:22
I commented your fork. Please perform recommended steps from comments.

**Comment by enriquesouza** [comment] 2019-02-14 19:37
@generalbytes , I commented back. My LOG files are just to debug. I will remove when this machine is in production, but sometimes the parameters comes null. I just saw that because of the LOG. Not sure if it was an issue before or if it was already solved, but was the only way I found to have this working.

**Comment by generalbytes** [comment] 2019-02-15 06:59
@enriquesouza You are making it really complicated to help you.

People fork code from repos to build on other's results. You seem to work in opposite direction.
Look for example here:
https://github.com/enriquesouza/batm_public/blob/master/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/common/AbstractRPCPaymentSupport.java

https://github.com/GENERALBYTESCOM/batm_public/blob/master/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/common/AbstractRPCPaymentSupport.java

Please go, clone both repos and use kdiff3 tool(diff folders) to see all changes you have made against main repo. You will spot issues that you are mixing in.

**Comment by enriquesouza** [comment] 2019-02-15 08:51
<img width="1661" alt="screen shot 2019-02-15 at 09 47 31" src="https://user-images.githubusercontent.com/1700699/52845260-f286dc00-3106-11e9-8609-77c3647c6317.png">
All differences are here. All commom libraries are up to date. 

Redeem still not work 

1) Read QR CODE - OK
2) BlockChain Check - ok
3) Payment arrived - ok
2) CashOut money from terminal - NOK

**Comment by generalbytes** [comment] 2019-02-15 20:21
Do you have better description of the problem than "4\. CashOut money from terminal - NOK"? 
Any logfiles? Or video?

**Comment by enriquesouza** [comment] 2019-02-16 11:36
@generalbytes , yes.
1) Video selling SmartCash in the Terminal
https://drive.google.com/open?id=1T4lpsQ2VZVJ7meBvEB46GDbNbMrUktwv

2) Status after sell in the ADMIN of the Terminal
https://drive.google.com/file/d/1lpFv6grHhb9fswxllmnyh-IVrIuoBkC2/view

3) Trying to Redeem
https://drive.google.com/file/d/1-Y1e0Bawpzl7bRqa3SLWW1a_ezDe9SGG/view

You can see that is blinks green, then red. 
I attached the green in this chat... the issue is when it is going to dispenser the money out of the machine.

<img width="1404" alt="screen shot 2019-02-16 at 12 35 28" src="https://user-images.githubusercontent.com/1700699/52899177-77492700-31e7-11e9-8738-66e4901d5193.png">

**Comment by enriquesouza** [comment] 2019-02-16 15:47
@generalbytes , the full process is now working.
It was a second dispenser that was not in place. Sorry about that.
https://drive.google.com/file/d/1h5y21zEOraGan34P6MaQpiY2j232WHpc/view?usp=sharing

**Comment by generalbytes** [comment] 2019-02-16 17:36
That is great news and excellent idea with Brazilian background music. I'm glad you managed to get Smartcash working. 
Don't forget to clean your code and create pull request so we can merge your changes into standard release which will be on Monday.

**Comment by enriquesouza** [comment] 2019-02-19 00:12
Thanks, @generalbytes . Heheh.. Yeah. Brazilian music to relax. :)
 It is working with the version 14022019. I forgot to pull request during the weekend. 
I will merge and retest it all.

**Comment by sumcoinlabs** [comment] 2019-02-20 07:05
Hi all.  

Hopefully this can be of some help to others who use a BTC based daemon.  We will continue to update the Wiki to make it as simple as possible and thanks to General Bytes team for the latter parts of it.  

https://github.com/sumcoinlabs/sumcoin/wiki/How-to-Setup-Sumcoin-For-General-Bytes-ATM's

Here’s the result: https://youtu.be/JooUOI0Db0g

**Closed** 2019-02-20 14:00 UTC
