### ISSUE TITLE
getIdentityRemainingLimits() throwing problem after its changed to ILimitExtended

### ISSUE THREAD

**Issue by mxicoderspl** [GENERALBYTESCOM/batm_public#795] opened 2023-03-16 07:44 UTC
Hello,
I created some functions which use getIdentityRemainingLimits() and that was working fine previously because previously it gave a list of IRemainingLimit but now the return type is changed of this method getIdentityRemainingLimits() so when I changed the return type to ILimitExtended and when I am fetching a value with the method getLimitType() or getAmount(). It always throws an Exception as:-"com.generalbytes.batm.server.extensions.a.a.x cannot be cast to com.generalbytes.batm.server.extensions.ILimitExtended".

Here we just want to get the particular amount for a particular LimitType but I am not getting why it is throwing an exception if I stored the whole list it is stored and we can fetch the whole list. But when we are trying to fetch a particular value through interface methods it is giving the exception.

**Comment by filipocelka** [comment] 2023-03-16 08:09
Hello Ashok,
this issue is caused by incompatibility between your server and the extension written based on one of the latest commits at master branch. 

Currently latest available version of the batm server application is `20230120` which is compatible with the code corresponding to tags 1.0.69-1.0.71 see https://github.com/GENERALBYTESCOM/batm_public/tags

Since you based your code on newer source code corresponding to tags 1.1.0+ you won't be able to use it at your server until newer version compatible with releases 1.1.0+ will be released to the public. Due to cast exception you mentioned.

I'm sorry for this inconvenience however there is a solution to this is issue. You can base your extension on the latest commit related to 1.0.71 version of batm_public: https://github.com/GENERALBYTESCOM/batm_public/releases/tag/1.0.71 i.e. commit `32c9983e0646fcb984f9af793e26e3ee9bcc1a4a`.

**Closed by filipocelka** 2023-03-16 08:09 UTC

**Comment by mxicoderspl** [comment] 2023-03-17 09:28
Thank you very much for your instant support It really helped us a lot.

**Comment by mxicoderspl** [comment] 2023-03-17 11:41
But after installing this we are facing this issue: so please can check why it is occurring -
`<html>
<body>


[/0.0.0.0/Master-start/1] c.g.batm.server.extensions.g - Failed to process extension server_extensions_extra-1.0.69.jarcom.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$UnknownFieldException: No such field com.generalbytes.batm.server.extensions.descriptor.ExtensionTag.identityverificationprovider---- Debugging information ----field : identityverificationproviderclass : com.generalbytes.batm.server.extensions.descriptor.ExtensionTagrequired-type : com.generalbytes.batm.server.extensions.descriptor.ExtensionTagconverter-type : com.thoughtworks.xstream.converters.reflection.ReflectionConverterpath : /extensions/extension[60]/identityverificationproviderclass[1] : com.generalbytes.batm.server.extensions.descriptor.ExtensionsTagversion : 1.4.7-------------------------------at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.handleUnknownField(AbstractReflectionConverter.java:495)at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:351)at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:257)at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:377)at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:257)at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1185)at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1169)at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1049)at com.generalbytes.batm.server.extensions.g.a(GB:537)at com.generalbytes.batm.server.extensions.g.a(GB:475)at com.generalbytes.batm.server.extensions.g.b(GB:3471)at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1580)at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)at com.generalbytes.batm.server.extensions.g.a(GB:232)at com.generalbytes.batm.server.extensions.g.a(GB:224)at com.generalbytes.batm.server.extensions.g.i(GB:194)at com.generalbytes.batm.server.extensions.g.b(GB:101)at com.generalbytes.batm.server.extensions.k.b(GB:111)at com.generalbytes.batm.server.services.g.b(GB:118)at com.generalbytes.batm.server.ServerMain.main(GB:9)
--
17.03.2023 11:28:33 | ERROR | [/0.0.0.0/Master-start/1] c.g.batm.server.extensions.g - Extension from file server_extensions_extra-1.0.69.jar could not be loaded.


</body>
</html>`

**Comment by mxicoderspl** [comment] 2023-03-17 11:43
![Screenshot (742)](https://user-images.githubusercontent.com/31618389/225895113-a959f3df-2560-4fd7-8d29-da85677c93aa.png)

**Comment by filipocelka** [comment] 2023-03-17 12:07
That is my fault. I'm really sorry for misleading you. 
Your server version `20230120` (I assume you use the lastest version `20230120.42`) is compatible with https://github.com/GENERALBYTESCOM/batm_public/releases/tag/1.0.69 so you should base your extension on commit `cf3bd46776a6bb36a937b6d883b16d8d68a7f12b` and ignore everything newer. Since there are still some features not available to you.

Again I'm sorry, I should've checked this more precisely.

**Comment by mxicoderspl** [comment] 2023-03-17 12:22
No, Issues,
But I want to ask that if there is only one issue about these 2 Extensions then I can comment these 2 extensions and then upload them to the server then it will not cause any new problems, Right??
